# Generated by Django 4.0.4 on 2022-05-26 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_city_options_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='career',
            field=models.ManyToManyField(null=True, to='person.career'),
        ),
        migrations.AlterField(
            model_name='city',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
