# Generated by Django 4.0.4 on 2022-05-26 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_career_person_person_career_alter_city_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.city'),
        ),
        migrations.AlterField(
            model_name='person',
            name='career',
            field=models.ManyToManyField(to='person.career'),
        ),
    ]
