# Generated by Django 4.0.4 on 2022-05-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_remove_city_person_person_city_alter_person_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='career',
        ),
        migrations.AddField(
            model_name='person',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.career'),
        ),
    ]
