# Generated by Django 4.0.4 on 2022-05-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_remove_person_career_person_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='career',
        ),
        migrations.AddField(
            model_name='person',
            name='career',
            field=models.ManyToManyField(to='person.career'),
        ),
    ]
