# Generated by Django 4.0.4 on 2022-05-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_album_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='area_of_study',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=10),
        ),
    ]
