# Generated by Django 4.0.4 on 2022-05-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_alter_career_area_of_study_alter_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
